### ISSUE TITLE
Fatal Error System.ArgumentOutOfRangeException:

### ISSUE THREAD

**Issue by GhostInTheMachines** [QuantumObject/docker-opensimulator#10]
I had this error on initial run of this image, I have attached the full console output in a separate file.  Have you seen this before?

Steps to reproduce:
1. docker run -d -p 9000:9000 -p 9000:9000/udp quantumobject/docker-opensimulator
2. rename image open_sim_initial
3. docker exec -it open_sim_initial after_install
4. Build seems to go fine, one error keeps repeating but has the caveat that if this is the first build it is ok.
5. Noticed this error that does not have a caveat.
08:06:12 - [MIGRATIONS]: Creating AuthStore at version 1
 no such table: users in SQL: BEGIN TRANSACTION; INSERT INTO auth (UUID, passwordHash, passwordSalt, webLoginKey) SELECT `UUID` AS UUID, `passwordHash` AS passwordHash, `passwordSalt` AS passwordSalt, `webLoginKey` AS webLoginKey FROM users; COMMIT; 
6. There are several other errors like this in the build (can be seen in the attached file)
7. I believe it gets to the configuration point but then has the fatal error listed below.

Fatal error: System.ArgumentOutOfRangeException: Value must be positive and below the buffer width.
Parameter name: left
[docker-opensimulator-error.txt](https://github.com/QuantumObject/docker-opensimulator/files/1754384/docker-opensimulator-error.txt)

I can contribute some time to this project if you are interested.

**Comment by angelrr7702** [comment]
did you build the container or did you used the quantumobject/docker-opensimulator image from docker repository ?

if you build it , maybe there was a update in the project and some procedure change .. that need to be update at quantumobject/docker-opensimulator .  I will check ....

Any help is welcome.

sincerely
Angel Rodriguez

**Comment by GhostInTheMachines** [comment]
I used the docker run command which pulls down the latest image from the docker repository.

Should I limit what version is pulled down specifically?

**Comment by angelrr7702** [comment]
Did the error happens before configuration question or after you have specified entry ..?

**Comment by GhostInTheMachines** [comment]
The error occurred just before the initial configuration, most likely just as it was about to ask the first question.

**Comment by tgiachi** [comment]
Same error here!

`03:56:27 - Fatal error: System.ArgumentOutOfRangeException: Value must be positive and below the buffer width.
Parameter name: left
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00021]: in <62f5937022004555807e6c57c33f6684>:0
  at System.TermInfoDriver.set_CursorLeft (System.Int32 value) [0x00016] in <62f5937022004555807e6c57c33f6684>:0
  at System.ConsoleDriver.set_CursorLeft (System.Int32 value) [0x00000] in <62f5937022004555807e6c57c33f6684>:0
  at System.Console.set_CursorLeft (System.Int32 value) [0x00000] in <62f5937022004555807e6c57c33f6684>:0
`

**Comment by angelrr7702** [comment]
Update to version 0.9.0.1

**Comment by angelrr7702** [comment]
Update to Version 0.9.1.1 , I tested and work fine for me .
