### ISSUE TITLE
This container consume to much resource from CPU

### ISSUE THREAD

**Issue by angelrr7702** [QuantumObject/docker-opensimulator#2]
When I check the Server where the container is running ... with top ,,, it very clear that almost all resource of the cpu been consume by mono  interpreter ,  including when nobody is accessing the container  virtual word.

partial solution : 

   - Define the cpu and memory this container will use when run command is used the first time.
   - Try to find a way that base of the port access the container is keep stop or start .. this maybe will help for use in all the container.

Solution:

   - Solution that is internally at container ... that improve the mono interpreter or change opensimulator conf that reduce the amount of resource use by it .

**Comment by giodegas** [comment]
I think it may be related on how this container is built.
My other [opensim-bin-standalone](http://registry.hub.docker.com/u/giodegas/opensim-bin-standalone/) container, based on debian wheezy, seems not to have this problem.

**Comment by angelrr7702** [comment]
I found the solution .. the problem is that opensim was writing to be interactive at terminal , it didn't suppose to be run in the background ... the only solutions I found online for this problem with mono was to use screen and them CPU  go from 102% to less than 6% and sometimes less than 1%.
