### ISSUE TITLE
pCampbot network packets from wrong IP

### ISSUE THREAD

**Issue by giodegas** [QuantumObject/docker-opensimulator#3]
Situation:
docker on a remote linux machine with public IP A
I did everything as explained in your instructions.
Local Singularity viewer correctly connects to the remote opensim uri http://<A address>:9000 and the world is correctly rendered.
Then I try to launch a remote NPC avatar using pCampBot running in the docker container with the following command:

```
docker exec -it <DOCKER_ID> mono /opt/opensim-0.8.1-rc2/bin/pCampBot.exe -l http://<A address>:9000 -s <Land name>/216/243/23 -firstname <FIRST> -lastname <LAST> -password <PASSWD> -b n
```

then I do

```
pCambot# connect
```

and a cloud starts to appear in the virtual world, but on the pCampbot console it keeps repeating:

```
13:01:03.568 - <FIRST LAST_0>: Received 12 bytes of data from unrecognized source 172.17.42.1:9000
```

not completing a proper login sequence.
On the opensim console I get:

```
12:59:18 - [LLUDPSERVER]: Handling CompleteAgentMovement request from 172.17.42.1:47694 in <LAND>
12:59:18 - [SCENE PRESENCE]: Completing movement of <FIRST LAST_0> into region <LAND> in position <216.046, 243.042, 23.02187>
12:59:18 - [SCENE PRESENCE]: Aborting CompleteMovement call for <FIRST LAST_0> into region <LAND>  as they are already root
13:00:06 - [SCENE]: Incoming client <FIRST LAST_0> into region <LAND>  via regular login. Client IP verification not performed.
13:00:10 - [LLUDPSERVER]: Received a resend of already processed packet #57, type AgentThrottle from <FIRST LAST_0>
13:00:10 - [LLUDPSERVER]: Received a resend of already processed packet #58, type AgentThrottle from <FIRST LAST_0>
13:00:11 - [LLUDPSERVER]: Received a resend of already processed packet #60, type AgentWearablesRequest from <FIRST LAST_0>
13:00:11 - [LLUDPSERVER]: Received a resend of already processed packet #59, type EconomyDataRequest from <FIRST LAST_0>
```

I think the problem is that the local viewer is correctly accessing the opensim server through the public IP, but the remote pCampbot client, from inside the container,  is connecting to the internal docker IP which does not corresponds with the one defined in Region.ini .

Is there any hope to get it work properly?

**Comment by angelrr7702** [comment]
Hi,
  Sorry , no that familiar with opensimulator options and software , I create this container to test it and learn more about it . I will try to make it work with Pcampbot . At the moment checking documentation about http://opensimulator.org/wiki/PCampBot ..

I will update if I found a solutions to this problem.

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
Hi,

 Did you can provide more info of the procedure you follow when this error appear ?

Did you create a pCampbot.ini file before execution of Pcampbot?

and

Did you create accounts for the bot with the form firstname lastname_0...n before execution of Pcampbot? and how did you do that ...

sincerely
Angel Rodriguez

**Comment by giodegas** [comment]
Yes, I followed instructions as explained there. This is my pCampbot.ini file:

    ; This is the example config file for pCampbot
    ; To use it, copy this file to pCampbot.ini and change settings if required
    
    [BotManager]
      ; Number of milliseconds to wait between bot logins
      LoginDelay = 5000
    
    [Bot]
      ; Control whether bots should regularly send agent updates
      ; Not doing this will reduce CPU requirements for pCampbot but greatly 
      ; reduce the realism compared to viewers which are constantly sending AgentUpdates UDP packets.
      ; Defaults to true.
      SendAgentUpdates = false

      ; Control whether bots will requests textures when receiving object information
      ; Not doing this will reduce CPU requirements for pCampbot but greatly 
      ; reduce the realism compared to viewers which requests such texture data if not already cached.
      ; Defaults to true.
      RequestObjectTextures = false

Yes, indeed, bot account is created and I can login in from the regular client.

**Comment by angelrr7702** [comment]
Update to version 0.9.0.1
