### ISSUE TITLE
Cannot exit after_install script

### ISSUE THREAD

**Issue by lazydino** [QuantumObject/docker-opensimulator#6]
The latest build won't exit from after_install, but the older test tag works fine. I am using docker 1.12.0

**Comment by angelrr7702** [comment]
Thanks , I will check,

**Comment by angelrr7702** [comment]
HI,

 yes. problem still present after update to last version ..0.9.0.0-rc

I have to kill process running another console by 

 docker exec it Container_ID /bin/bash 
 top 
 kill -9 <process id for ./opensim-ode.sh>


 
that will allow after_install script to continue ...

problem relate to 

http://opensimulator.org/mantis/view.php?id=7743

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
This was fix after update .
