### ISSUE TITLE
getting an error message when running after_install

### ISSUE THREAD

**Issue by wjgeorge** [QuantumObject/docker-opensimulator#9]
We are now going to ask a couple of questions about your region.

You can press 'enter' without typing anything to use the default

the default is displayed between [ ] brackets.

=====================================

01:57:53 - Fatal error: System.ArgumentOutOfRangeException: Value must be positive and below the buffer width.
Parameter name: left
  at System.TermInfoDriver.SetCursorPosition (System.Int32 left, System.Int32 top) [0x00021]: in <62f5937022004555807e6c57c33f6684>:0 
  at System.TermInfoDriver.set_CursorLeft (System.Int32 value) [0x00016] in <62f5937022004555807e6c57c33f6684>:0

**Comment by angelrr7702** [comment]
There are some options that default is the wrong response : 

External host name [SYSTEMIP]: ==> need to entry the external ip or your http address don't include the port.

if running directly from local linux computer that you will running the same viewer you can used 0.0.0.0 but if server (this container) is running from other computer than the viewer need to used the external ip for the server or http:// address for it.

 please check the README.md file .. at https://github.com/QuantumObject/docker-opensimulator

if still fail please send me example for your configuration with info of the system you running your container ..

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
I have to edit the prior response .I tested and working fine ..

**Comment by wjgeorge** [comment]
Are you running docker-ce?

Also you can’t use Home, but need to use the region name. Firefox tries to load something external if you use home

**Comment by angelrr7702** [comment]
yes. I running docker community edition. 

Firefox tries to load something external if you use home.  ==> ?
no sure what you mean ... this container have a web page :

"
Ooops!

The page you requested has been obsconded with by knomes. Find hippos quick!

If you are trying to log-in, your link parameters should have: "-loginpage http:///?method=login -loginuri http:///" in your link

"
that is normal ... this container is to be used with viewer like secondlife viewer .. no Firefox

sincerely
Angel Rodriguez

**Comment by wjgeorge** [comment]
Sorry, I meant FireStorm. It’s  not a problem with your container, so I’m closing the ticket. I’ve modified my Docker file to update the .ini so I don’t need to have OpenSimulator ask the questions
